# Generated by Django 4.0.1 on 2022-03-18 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termine',
            fields=[
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung *')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Datum *')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Standort')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('bild', models.ImageField(upload_to='', verbose_name='Bild *')),
                ('beschreibung', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beschreibung')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standort', models.CharField(blank=True, max_length=50, null=True, verbose_name='Standort')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('titel', models.CharField(max_length=50, verbose_name='Titel *')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('inhalt', models.CharField(max_length=2000, verbose_name='Inhalt *')),
                ('bild', models.ImageField(blank=True, default='tennisball.png', upload_to='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Datum *')),
                ('standort', models.CharField(blank=True, max_length=50, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
