# Generated by Django 4.0.1 on 2022-03-19 23:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tennisclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('autor', models.CharField(max_length=100, verbose_name='Anzeigename *')),
                ('inhalt', models.CharField(max_length=200, verbose_name='Inhalt *')),
                ('date', models.DateField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blogPost_reffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennisclub.blogpost')),
            ],
        ),
    ]
